version: 2
updates:
  - package-ecosystem: "pip" # Cambia por npm, yarn, etc.
    directory: "/" # Carpeta donde está tu archivo requirements.txt
    schedule:
      interval: "daily" # Frecuencia de comprobación
