services:
  ytextractor:
    container_name: ytextractor
    build: .
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    networks: [tunnel]

networks:
  tunnel:
    external: true
