services:
  ytextractor:
    container_name: ytextractor
    build: .
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks: [tunnel]
    restart: unless-stopped

networks:
  tunnel:
    external: true
